-- =============================================================================
-- Token Limits Setup
-- Creates tables to track per-user token usage and configure limits.
-- Run as TEST user via SQLcl.
-- =============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON

-- -----------------------------------------------------------------------------
-- Table: UC_AI_TOKEN_USAGE
-- Append-only log of every chatbot request with token consumption.
-- -----------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE uc_ai_token_usage PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE uc_ai_token_usage (
  id               NUMBER         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  apex_user        VARCHAR2(255)  NOT NULL,
  apex_session_id  VARCHAR2(100),
  prompt_tokens    NUMBER         DEFAULT 0 NOT NULL,
  completion_tokens NUMBER        DEFAULT 0 NOT NULL,
  reasoning_tokens NUMBER         DEFAULT 0 NOT NULL,
  total_tokens     NUMBER         DEFAULT 0 NOT NULL,
  tool_calls_count NUMBER         DEFAULT 0 NOT NULL,
  model            VARCHAR2(100),
  provider         VARCHAR2(50),
  created_at       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE  uc_ai_token_usage                  IS 'Append-only log of every UC AI chatbot request with token consumption per APEX user.';
COMMENT ON COLUMN uc_ai_token_usage.apex_user        IS 'APEX application user (APP_USER) who sent the request.';
COMMENT ON COLUMN uc_ai_token_usage.apex_session_id  IS 'APEX session ID for debugging.';
COMMENT ON COLUMN uc_ai_token_usage.prompt_tokens    IS 'Input tokens sent to the model (system prompt + history + tools).';
COMMENT ON COLUMN uc_ai_token_usage.completion_tokens IS 'Output tokens generated by the model.';
COMMENT ON COLUMN uc_ai_token_usage.reasoning_tokens IS 'Thinking/reasoning tokens (Gemini 2.5 only).';
COMMENT ON COLUMN uc_ai_token_usage.total_tokens     IS 'Total tokens = prompt + completion + reasoning.';
COMMENT ON COLUMN uc_ai_token_usage.tool_calls_count IS 'Number of tool calls made during this request.';

CREATE INDEX uc_ai_token_usage_user_date_ix
    ON uc_ai_token_usage (apex_user, trunc(created_at));

-- -----------------------------------------------------------------------------
-- Table: UC_AI_TOKEN_LIMITS
-- Configurable per-period token and request quotas.
-- One row per period type (DAILY / WEEKLY).
-- -----------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE uc_ai_token_limits PURGE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE uc_ai_token_limits (
  id           NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  period_type  VARCHAR2(10)  NOT NULL,
  max_tokens   NUMBER        NOT NULL,
  max_requests NUMBER,
  is_active    VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
  description  VARCHAR2(200),
  CONSTRAINT uc_ai_token_limits_period_ck  CHECK (period_type IN ('DAILY', 'WEEKLY')),
  CONSTRAINT uc_ai_token_limits_active_ck  CHECK (is_active   IN ('Y', 'N')),
  CONSTRAINT uc_ai_token_limits_period_uq  UNIQUE (period_type)
);

COMMENT ON TABLE  uc_ai_token_limits             IS 'Configurable per-period token and request quotas for the UC AI chatbot.';
COMMENT ON COLUMN uc_ai_token_limits.period_type IS 'Quota period: DAILY or WEEKLY.';
COMMENT ON COLUMN uc_ai_token_limits.max_tokens  IS 'Maximum total tokens allowed per user per period (0 = unlimited).';
COMMENT ON COLUMN uc_ai_token_limits.max_requests IS 'Maximum number of chatbot calls per user per period (null = no limit).';
COMMENT ON COLUMN uc_ai_token_limits.is_active   IS 'Y = limit is enforced; N = limit is disabled (monitoring only).';

-- Seed with sensible defaults — adjust as needed.
INSERT INTO uc_ai_token_limits (period_type, max_tokens, max_requests, is_active, description)
VALUES ('DAILY',  50000, 30, 'Y', 'Max 50 000 tokens and 30 requests per user per day');

INSERT INTO uc_ai_token_limits (period_type, max_tokens, max_requests, is_active, description)
VALUES ('WEEKLY', 200000, 100, 'Y', 'Max 200 000 tokens and 100 requests per user per week');

COMMIT;

BEGIN
  DBMS_OUTPUT.PUT_LINE('Tables UC_AI_TOKEN_USAGE and UC_AI_TOKEN_LIMITS created and seeded successfully.');
END;
/
